-- AlterEnum
-- PostgreSQL: ADD VALUE는 트랜잭션 밖에서 실행해야 함
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'REPAIR_OWNER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'REPAIR_TECH';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'AP_USER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'APPROVER';
