name: Build and Push to Artifact Registry

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Workload Identity Federation을 사용하기 위한 권한 설정
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Google Cloud 인증 (Workload Identity Federation)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/480495809237/locations/global/workloadIdentityPools/junoh-github-pool/providers/github'
          service_account: 'junolee1@assemanagement.iam.gserviceaccount.com'
      # 2. Docker가 asia-northeast3-docker.pkg.dev 레지스트리에 접근할 수 있도록 인증 설정
      - name: Configure Docker to use Google Cloud Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        env:
          PROJECT_ID: assemanagement
          REGION: asia-northeast3
          REPOSITORY: asset-erp-backend
          IMAGE_NAME: asset-erp-backend
        run: |
          # 이미지 태그 생성 (Commit SHA 활용 등)
          IMAGE_TAG="${{ region }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          
          # Docker 빌드
          docker build -t $IMAGE_TAG .
          
          # Artifact Registry로 푸시
          docker push $IMAGE_TAG